using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Tao.OpenGl;
using Tao.FreeGlut;
using Tao.Platform.Windows;
using Tao.DevIl;
using System.Drawing;
using SweetHome3D.Furniture;
namespace SweetHome3D
{
    [Serializable]
    public class ShelfForShoes : FurnitureObject  
    {
        public ShelfForShoes()
        {
            Location = new Point(0, 0);
            Height = 70;
            Width = 92;
            Depth = 46;
            Angle = 0;
            TypeName = "ShelfForShoes";
            Name = "Подставка";
            AddressOfTheImageTexture = @"ShelfForShoes\1.jpg";
        }

        public override void Draw()
        {
            Width /= 2;
            Depth /= 2;
            //1-я ножка
            Gl.glEnable(Gl.GL_TEXTURE_2D);
            Gl.glDisable(Gl.GL_TEXTURE_GEN_S);
            Gl.glDisable(Gl.GL_TEXTURE_GEN_T);
            Gl.glBindTexture(Gl.GL_TEXTURE_2D, Texture);

            Gl.glPushMatrix();
            if (Angle == 0 || Angle == 180)
                Gl.glTranslated(Location.X - Width, 0, Location.Y - Depth + 5);
            else
                Gl.glTranslated(Location.X - Depth, 0, Location.Y - Width);
            Gl.glRotated(Angle, 0, 1, 0);

            Gl.glColor3d(1.0, 1.0, 1.0);
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(Width, 0, Depth);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(Width, 2, Depth);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(Width, 2, -Depth);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(Width, 0, -Depth);
            Gl.glEnd();

            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(Width-2, 0, 23);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(Width - 2, 2, 23);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(Width - 2, 2, -23);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(Width - 2, 0, -23);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(Width, 2, 23);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(Width - 2, 2, 23);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(Width - 2, 2, -23);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(Width, 2, -23);
            Gl.glEnd();

            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(46, 2, 23);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(44, 2, 23);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(44, 0, 23);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(46, 0, 23);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(46, 2, -23);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(44, 2, -23);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(44, 0, -23);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(46, 0, -23);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(46, 0, 7);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(46, Height, 7);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(46, Height, 5);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(46, 0, 5);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(44, 0, 7);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(44, Height, 7);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(44, Height, 5);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(44, 0, 5);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(46, 0, -7);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(46, Height, -7);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(46, Height, -5);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(46, 0, -5);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(44, 0, -7);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(44, Height, -7);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(44, Height, -5);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(44, 0, -5);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(44, 0, 7);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(44, Height, 7);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(46, Height, 7);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(46, 0, 7);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(44, 0, -7);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(44, Height, -7);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(46, Height, -7);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(46, 0, -7);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(44, 0, 5);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(44, Height, 5);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(46, Height, 5);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(46, 0, 5);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(44, 0, -5);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(44, Height, -5);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(46, Height, -5);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(46, 0, -5);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(46, Height, 7);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(44, Height, 7);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(44, Height, -7);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(46, Height, -7);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(46, Height - 2, 7);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(44, Height - 2, 7);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(44, Height - 2, -7);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(46, Height - 2, -7);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(46, Height - 2, 7);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(46, Height - 2, -7);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(46, Height, -7);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(46, Height , 7);
            Gl.glEnd();
            //2-я ножка
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(-46, 0, 23);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(-46, 2, 23);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(-46, 2, -23);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(-46, 0, -23);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(-44, 0, 23);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(-44, 2, 23);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(-44, 2, -23);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(-44, 0, -23);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(-46, 2, 23);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(-44, 2, 23);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(-44, 2, -23);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(-46, 2, -23);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(-46, 2, 23);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(-44, 2, 23);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(-44, 0, 23);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(-46, 0, 23);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(-46, 2, -23);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(-44, 2, -23);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(-44, 0, -23);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(-46, 0, -23);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(-46, 0, 7);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(-46, Height, 7);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(-46, Height, 5);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(-46, 0, 5);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(-44, 0, 7);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(-44, Height, 7);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(-44, Height, 5);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(-44, 0, 5);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(-46, 0, -7);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(-46, Height, -7);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(-46, Height, -5);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(-46, 0, -5);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(-44, 0, -7);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(-44, Height, -7);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(-44, Height, -5);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(-44, 0, -5);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(-44, 0, 7);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(-44, Height, 7);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(-46, Height, 7);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(-46, 0, 7);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(-44, 0, -7);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(-44, Height, -7);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(-46, Height, -7);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(-46, 0, -7);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(-44, 0, 5);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(-44, Height, 5);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(-46, Height, 5);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(-46, 0, 5);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(-44, 0, -5);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(-44, Height, -5);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(-46, Height, -5);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(-46, 0, -5);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(-46, Height, 7);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(-44, Height, 7);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(-44, Height, -7);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(-46, Height, -7);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(-46, Height - 2, 7);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(-44, Height - 2, 7);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(-44, Height - 2, -7);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(-46, Height - 2, -7);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(-46, Height - 2, 7);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(-46, Height - 2, -7);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(-46, Height, -7);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(-46, Height, 7);
            Gl.glEnd();
            Gl.glDisable(Gl.GL_TEXTURE_2D);
            //1-я подставка
            Gl.glEnable(Gl.GL_TEXTURE_2D);
            Gl.glDisable(Gl.GL_TEXTURE_GEN_S);
            Gl.glDisable(Gl.GL_TEXTURE_GEN_T);
               //Gl.glBindTexture(GL_TEXTURE_2D, textures[4]);
            Gl.glColor3d(1.0, 1.0, 1.0);
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(43.9, Height - 65, -18);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(43.9, Height - 60, 18);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(-43.9,Height - 60, 18);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(-43.9,Height - 65, -18);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glColor3d(0.8, 0.8, 0.8);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(43.9, Height-65, -18);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(43.9, Height-62, -18);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(43.9, Height-57, 18);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(43.9, Height-60, 18);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(-43.9, Height-65, -18);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(-43.9, Height-62, -18);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(-43.9, Height-57, 18);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(-43.9, Height-60, 18);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(43.9, Height-65, -18);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(43.9, Height-62, -18);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(-43.9,Height-62, -18);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(-43.9,Height-65, -18);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(43.9, Height-60, 18);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(43.9, Height-55, 18);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(-43.9,Height-55, 18);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(-43.9,Height-60, 18);
            Gl.glEnd();
            Gl.glColor3d(1.0, 1.0, 1.0);
            //2-я подставка
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(43.9, Height-35, -18);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(43.9, Height-30, 18);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(-43.9,Height-30, 18);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(-43.9,Height-35, -18);
            Gl.glEnd();
            Gl.glColor3d(0.8, 0.8, 0.8);
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(43.9, Height-35, -18);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(43.9, Height-32, -18);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(43.9, Height-27, 18);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(43.9, Height-30, 18);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(-43.9, Height-35, -18);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(-43.9, Height-32, -18);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(-43.9, Height-27, 18);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(-43.9, Height-30, 18);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(43.9, Height-35, -18);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(43.9, Height-32, -18);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(-43.9,Height-32, -18);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(-43.9,Height-35, -18);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(43.9, Height-30, 18);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(43.9, Height-30, 18);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(43.9, Height-25, 18);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(-43.9,Height-25, 18);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(-43.9,Height-30, 18);
            Gl.glEnd();
            Gl.glColor3d(1.0, 1.0, 1.0);
            //3-я подставка
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(43.9, Height-5, -18);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(43.9, Height, 18);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(-43.9, Height, 18);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(-43.9, Height-5, -18);
            Gl.glEnd();
            Gl.glColor3d(0.8, 0.8, 0.8);
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(43.9, Height-5, -18);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(43.9, Height-2, -18);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(43.9, Height+3, 18);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(43.9, Height, 18);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(-43.9, Height-5, -18);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(-43.9, Height-2, -18);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(-43.9, Height+3, 18);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(-43.9, Height, 18);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(43.9, Height-5, -18);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(43.9, Height-2, -18);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(-43.9, Height-2, -18);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(-43.9, Height-5, -18);
            Gl.glEnd();
            Gl.glBegin(Gl.GL_QUADS);
            Gl.glTexCoord2d(0, 0); Gl.glVertex3d(43.9, Height, 18);
            Gl.glTexCoord2d(0, 1); Gl.glVertex3d(43.9, Height+5, 18);
            Gl.glTexCoord2d(1, 1); Gl.glVertex3d(-43.9, Height+5, 18);
            Gl.glTexCoord2d(1, 0); Gl.glVertex3d(-43.9, Height, 18);
            Gl.glEnd();
            Gl.glColor3d(1.0, 1.0, 1.0);
            Gl.glPopMatrix();
            Gl.glDisable(Gl.GL_TEXTURE_2D);
            Width *= 2;
            Depth *= 2;
        }
    }
}
